version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: resume
    ports:
      - "9001:80"
    volumes:
      - /home/docker/config/resume/www:/usr/share/nginx/html:ro
      - /home/docker/config/resume/nginx:/etc/nginx/conf.d/:ro
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
cloudflared:
    image: cloudflare/cloudflared:2022.5.3
    command: tunnel --no-autoupdate run --token ${cloudflared_token}
    restart: unless-stopped
